export const CLIENT_BOOKING_REQUEST = "CLIENT_BOOKING_REQUEST";
export const CLIENT_BOOKING_SUCCESS = "CLIENT_BOOKING_SUCCESS";
export const CLIENT_BOOKING_FAIL = "CLIENT_BOOKING_FAIL";

export const CLIENT_DELETE_REQUEST = "CLIENT_DELETE_REQUEST";
export const CLIENT_DELETE_SUCCESS = "CLIENT_DELETE_SUCCESS";
export const CLIENT_DELETE_FAIL = "CLIENT_DELETE_FAIL";

export const CLIENT_EDIT_REQUEST = "CLIENT_EDIT_REQUEST";
export const CLIENT_EDIT_SUCCESS = "CLIENT_EDIT_SUCCESS";
export const CLIENT_EDIT_FAIL = "CLIENT_EDIT_FAIL";
